#############################################################################
# Makefile for building: keyring_example
# Generated by qmake (2.01a) (Qt 4.8.4) on: Tue Jan 29 11:00:12 2013
# Project:  keyring_example.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile keyring_example.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQXT_CORE_LIB -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I/usr/include/qt4/QxtCore -I/usr/include/qxt -I/usr/include/qxt/QxtCore -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lQxtCore -lQtDBus -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		keyring_manager.cpp \
		keyring/collection.cpp \
		keyring/interface_factory.cpp \
		keyring/item.cpp \
		keyring/keyring.cpp \
		keyring/keyring_signal_mapper.cpp \
		keyring/prompt.cpp \
		keyring/secret.cpp \
		keyring/service.cpp \
		keyring/session.cpp \
		dbus/dbus_helper.cpp \
		dbus/signal_mapper.cpp moc_keyring_manager.cpp \
		moc_async_call_data.cpp \
		moc_collection.cpp \
		moc_item.cpp \
		moc_prompt.cpp \
		moc_service.cpp \
		moc_session.cpp \
		moc_dbus_helper.cpp
OBJECTS       = main.o \
		keyring_manager.o \
		collection.o \
		interface_factory.o \
		item.o \
		keyring.o \
		keyring_signal_mapper.o \
		prompt.o \
		secret.o \
		service.o \
		session.o \
		dbus_helper.o \
		signal_mapper.o \
		moc_keyring_manager.o \
		moc_async_call_data.o \
		moc_collection.o \
		moc_item.o \
		moc_prompt.o \
		moc_service.o \
		moc_session.o \
		moc_dbus_helper.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qxtvars.prf \
		/usr/share/qt4/mkspecs/features/qxt.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		keyring_example.pro
QMAKE_TARGET  = keyring_example
DESTDIR       = 
TARGET        = keyring_example

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: keyring_example.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qxtvars.prf \
		/usr/share/qt4/mkspecs/features/qxt.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtDBus.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile keyring_example.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qxtvars.prf:
/usr/share/qt4/mkspecs/features/qxt.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtDBus.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile keyring_example.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/keyring_example1.0.0 || $(MKDIR) .tmp/keyring_example1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/keyring_example1.0.0/ && $(COPY_FILE) --parents keyring_manager.h keyring/async_call_data.h keyring/collection.h keyring/interface_factory.h keyring/item.h keyring/keyring.h keyring/keyring_signal_mapper.h keyring/prompt.h keyring/secret.h keyring/service.h keyring/session.h dbus/dbus_helper.h dbus/signal_mapper.h .tmp/keyring_example1.0.0/ && $(COPY_FILE) --parents main.cpp keyring_manager.cpp keyring/collection.cpp keyring/interface_factory.cpp keyring/item.cpp keyring/keyring.cpp keyring/keyring_signal_mapper.cpp keyring/prompt.cpp keyring/secret.cpp keyring/service.cpp keyring/session.cpp dbus/dbus_helper.cpp dbus/signal_mapper.cpp .tmp/keyring_example1.0.0/ && (cd `dirname .tmp/keyring_example1.0.0` && $(TAR) keyring_example1.0.0.tar keyring_example1.0.0 && $(COMPRESS) keyring_example1.0.0.tar) && $(MOVE) `dirname .tmp/keyring_example1.0.0`/keyring_example1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/keyring_example1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_keyring_manager.cpp moc_async_call_data.cpp moc_collection.cpp moc_item.cpp moc_keyring.cpp moc_keyring_signal_mapper.cpp moc_prompt.cpp moc_service.cpp moc_session.cpp moc_dbus_helper.cpp moc_signal_mapper.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_keyring_manager.cpp moc_async_call_data.cpp moc_collection.cpp moc_item.cpp moc_keyring.cpp moc_keyring_signal_mapper.cpp moc_prompt.cpp moc_service.cpp moc_session.cpp moc_dbus_helper.cpp moc_signal_mapper.cpp
moc_keyring_manager.cpp: keyring/keyring.h \
		keyring/secret.h \
		dbus/dbus_helper.h \
		keyring_manager.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring_manager.h -o moc_keyring_manager.cpp

moc_async_call_data.cpp: keyring/async_call_data.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/async_call_data.h -o moc_async_call_data.cpp

moc_collection.cpp: keyring/secret.h \
		dbus/dbus_helper.h \
		keyring/collection.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/collection.h -o moc_collection.cpp

moc_item.cpp: keyring/secret.h \
		dbus/dbus_helper.h \
		keyring/item.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/item.h -o moc_item.cpp

moc_keyring.cpp: keyring/secret.h \
		dbus/dbus_helper.h \
		keyring/keyring.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/keyring.h -o moc_keyring.cpp

moc_keyring_signal_mapper.cpp: keyring/keyring_signal_mapper.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/keyring_signal_mapper.h -o moc_keyring_signal_mapper.cpp

moc_prompt.cpp: keyring/prompt.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/prompt.h -o moc_prompt.cpp

moc_service.cpp: keyring/secret.h \
		dbus/dbus_helper.h \
		keyring/service.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/service.h -o moc_service.cpp

moc_session.cpp: keyring/secret.h \
		dbus/dbus_helper.h \
		keyring/session.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) keyring/session.h -o moc_session.cpp

moc_dbus_helper.cpp: dbus/dbus_helper.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dbus/dbus_helper.h -o moc_dbus_helper.cpp

moc_signal_mapper.cpp: dbus/signal_mapper.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dbus/signal_mapper.h -o moc_signal_mapper.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp keyring_manager.h \
		keyring/keyring.h \
		keyring/secret.h \
		dbus/dbus_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

keyring_manager.o: keyring_manager.cpp keyring_manager.h \
		keyring/keyring.h \
		keyring/secret.h \
		dbus/dbus_helper.h \
		/usr/include/qxt/QxtCore/QxtLogger \
		/usr/include/qxt/QxtCore/qxtlogger.h \
		/usr/include/qxt/QxtCore/qxtglobal.h \
		/usr/include/qxt/QxtCore/qxtlogstream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyring_manager.o keyring_manager.cpp

collection.o: keyring/collection.cpp keyring/collection.h \
		keyring/secret.h \
		dbus/dbus_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collection.o keyring/collection.cpp

interface_factory.o: keyring/interface_factory.cpp keyring/interface_factory.h \
		keyring/collection.h \
		keyring/secret.h \
		dbus/dbus_helper.h \
		keyring/item.h \
		keyring/service.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interface_factory.o keyring/interface_factory.cpp

item.o: keyring/item.cpp keyring/item.h \
		keyring/secret.h \
		dbus/dbus_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o keyring/item.cpp

keyring.o: keyring/keyring.cpp /usr/include/qxt/QxtCore/QxtLogger \
		/usr/include/qxt/QxtCore/qxtlogger.h \
		/usr/include/qxt/QxtCore/qxtglobal.h \
		/usr/include/qxt/QxtCore/qxtlogstream.h \
		/usr/include/qxt/QxtCore/QxtJSON \
		/usr/include/qxt/QxtCore/qxtjson.h \
		dbus/signal_mapper.h \
		keyring/async_call_data.h \
		keyring/collection.h \
		keyring/secret.h \
		dbus/dbus_helper.h \
		keyring/interface_factory.h \
		keyring/item.h \
		keyring/service.h \
		keyring/prompt.h \
		keyring/session.h \
		keyring/keyring_signal_mapper.h \
		keyring/keyring.h \
		moc_keyring.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyring.o keyring/keyring.cpp

keyring_signal_mapper.o: keyring/keyring_signal_mapper.cpp keyring/keyring_signal_mapper.h \
		moc_keyring_signal_mapper.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyring_signal_mapper.o keyring/keyring_signal_mapper.cpp

prompt.o: keyring/prompt.cpp keyring/prompt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prompt.o keyring/prompt.cpp

secret.o: keyring/secret.cpp keyring/secret.h \
		dbus/dbus_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o secret.o keyring/secret.cpp

service.o: keyring/service.cpp keyring/service.h \
		keyring/secret.h \
		dbus/dbus_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o service.o keyring/service.cpp

session.o: keyring/session.cpp keyring/session.h \
		keyring/secret.h \
		dbus/dbus_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o session.o keyring/session.cpp

dbus_helper.o: dbus/dbus_helper.cpp dbus/dbus_helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbus_helper.o dbus/dbus_helper.cpp

signal_mapper.o: dbus/signal_mapper.cpp dbus/signal_mapper.h \
		moc_signal_mapper.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signal_mapper.o dbus/signal_mapper.cpp

moc_keyring_manager.o: moc_keyring_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyring_manager.o moc_keyring_manager.cpp

moc_async_call_data.o: moc_async_call_data.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_async_call_data.o moc_async_call_data.cpp

moc_collection.o: moc_collection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_collection.o moc_collection.cpp

moc_item.o: moc_item.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_item.o moc_item.cpp

moc_prompt.o: moc_prompt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prompt.o moc_prompt.cpp

moc_service.o: moc_service.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_service.o moc_service.cpp

moc_session.o: moc_session.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_session.o moc_session.cpp

moc_dbus_helper.o: moc_dbus_helper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbus_helper.o moc_dbus_helper.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

