######################################################################
# Automatically generated by qmake (3.0) Mon Mar 4 23:54:23 2013
######################################################################

QT += testlib
CONFIG += testcase

TEMPLATE = app
TARGET = tests

INCLUDEPATH += ../ sso_api

LIBS += ../lib/libssolib.a

# Input
HEADERS += sso_api/*.h
SOURCES += main.cpp \
    sso_api/*.cpp
