######################################################################
# Automatically generated by qmake (3.0) Mon Mar 4 23:54:23 2013
######################################################################

QT += testlib
CONFIG += testcase
# Include the rpath libdir to run the test program
CONFIG += rpath_libdirs
QMAKE_LFLAGS += "-Wl,-rpath,../lib"

TEMPLATE = app
TARGET = tests

INCLUDEPATH += ../ sso_api

LIBS += -L../lib -lssolib

# Input
HEADERS += sso_api/*.h
SOURCES += main.cpp \
    sso_api/*.cpp
