/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c UserAdaptor -a user_adaptor.h:user_adaptor.cpp com.ubuntu.sso.User.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "user_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UserAdaptor
 */

UserAdaptor::UserAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UserAdaptor::~UserAdaptor()
{
    // destructor
}

bool UserAdaptor::sessionOpened()
{
    // handle method call com.ubuntu.sso.User.sessionOpened
    bool opened;
    QMetaObject::invokeMethod(parent(), "sessionOpened", Q_RETURN_ARG(bool, opened));
    return opened;
}

