/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c UserAdaptor -a user_adaptor.h:user_adaptor.cpp com.ubuntu.sso.User.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef USER_ADAPTOR_H_1359986477
#define USER_ADAPTOR_H_1359986477

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.ubuntu.sso.User
 */
class UserAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.ubuntu.sso.User")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.ubuntu.sso.User\">\n"
"    <method name=\"sessionOpened\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"opened\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    UserAdaptor(QObject *parent);
    virtual ~UserAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool sessionOpened();
Q_SIGNALS: // SIGNALS
};

#endif
