######################################################################
# Automatically generated by qmake (3.0) Tue Mar 5 00:07:57 2013
######################################################################

QT += core network

TEMPLATE = app
TARGET = app

INCLUDEPATH += ../lib

LIBS += ../lib/libssolib.a

SOURCES += main.cpp
