#!/bin/bash

if [[ -z `which autopilot` ]]; then
  echo "Autopilot is not installed. Skip"
  exit
fi

SCRIPTPATH=`dirname $0`
pushd ${SCRIPTPATH}

if [ "x$2" == "xlocal" ]; then
  echo "Using server at localhost:8080"
  export SSO_AUTH_BASE_URL=http://localhost:8080
  export SSO_UONE_BASE_URL=http://localhost:8080
  python run_mock_server.py &
fi

export QML2_IMPORT_PATH=/usr/lib/i386-linux-gnu/ubuntu-system-settings/private:$1/../../qml-credentials-service
export U1_DEBUG=1
autopilot run UbuntuOneCredentialsProviderAutopilotTests
popd

if [ "x$2" == "xlocal" ]; then
  echo "tearing down server"
  kill -HUP %1
fi
