#!/bin/bash

if [[ -z `which autopilot` ]]; then
  echo "Autopilot is not installed. Skip"
  exit
fi

SCRIPTPATH=`dirname $0`
pushd ${SCRIPTPATH}
export QML2_IMPORT_PATH=$QML2_IMPORT_PATH:/usr/lib/i386-linux-gnu/ubuntu-system-settings/private
autopilot run UbuntuOneCredentialsProviderAutopilotTests
popd
